// Generated by CoffeeScript 1.8.0
(function() {
  var $, $a, $b, $d, A, Aa, Ab, Ac, Ad, B, Ba, Bb, Bc, Bd, C, Ca, Cb, Cc, Cd, D, Da, Db, Dc, E, Ea, Eb, Ec, Ed, F, FOO, Fa, Fb, Fc, Fd, G, Ga, Gb, Gc, H, Ha, Hb, Hc, Hd, I, Ia, Ib, Ic, Id, J, Ja, Jb, Jc, Jd, K, Ka, Kb, Kc, Kd, L, La, Lb, Lc, Ld, M, Ma, Mb, Mc, Md, N, Na, Nb, Nc, O, Oa, Ob, Oc, Od, P, Pa, Pb, Pc, Pd, Q, Qa, Qb, Qc, Qd, R, Ra, Rb, Rc, Rd, S, Sa, Sb, Sc, Sd, T, Ta, Tb, Tc, U, Ua, Ub, Uc, V, Va, Vb, Vc, Vd, W, Wa, Wb, Wc, Wd, X, Xa, Xb, Xc, Y, Ya, Yb, Yc, Yd, Z, Za, Zb, Zc, Zd, aa, ab, ac, ad, ae, ano, ba, bb, bc, bd, cb, cc, cd, da, db, dc, dd, eb, ec, ed, f, fa, fb, fc, fd, ga, gb, gc, gd, h, ha, hb, hc, hd, ia, ib, ic, id, is_boolean, is_function, is_object, ja, jb, jc, jd, ka, kb, kc, kd, la, lb, lc, ld, m, ma, mb, mc, md, n, na, nb, nc, nd, oa, ob, oc, od, p, pa, pb, pc, pd, q, qa, qb, qc, qd, r, ra, rb, rc, rd, s, sa, sb, sc, sd, t, ta, tb, tc, td, u, ua, ub, uc, ud, v, va, vb, vc, wa, wb, wc, wd, x, xa, xb, xc, xd, y, ya, yb, yc, yd, z, za, zb, zc, zd,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  aa = encodeURIComponent;

  f = window;

  ba = setTimeout;

  n = Math;

  Pc = function(a, b) {
    return a.href = b;
  };

  fa = function(a, b) {
    return a.name = b;
  };

  Qc = "replace";

  q = "data";

  m = "match";

  xc = "send";

  ja = "port";

  u = "createElement";

  id = "setAttribute";

  da = "getTime";

  x = "host";

  A = "split";

  B = "location";

  ra = "hasOwnProperty";

  ma = "hostname";

  ga = "search";

  E = "protocol";

  Ab = "href";

  kd = "action";

  G = "apply";

  p = "push";

  h = "hash";

  s = "test";

  ha = "slice";

  r = "cookie";

  t = "indexOf";

  ia = "defaultValue";

  v = "name";

  y = "length";

  z = "prototype";

  la = "clientWidth";

  jd = "target";

  C = "call";

  na = "clientHeight";

  F = "substring";

  oa = "navigator";

  Ub = "parentNode";

  H = "join";

  I = "toLowerCase";

  FOO = (function() {
    function FOO() {

      /*
       */
      this.a = [];
    }

    FOO.prototype.set = function(b) {

      /*
       */
      return this.a[b] = true;
    };

    FOO.prototype.M = function() {

      /*
       */
      var all_allowed_characters, b, counter, divided_counter, divided_counter_rest, divided_floor_counter;
      all_allowed_characters = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_";
      b = [];
      counter = -1;
      while (counter < a.length) {
        counter++;
        if (this.a[counter]) {
          divided_counter = counter / 6;
          divided_counter_rest = counter % 6;
          divided_floor_counter = Math.floor(divided_counter);
          b[divided_floor_counter] = b[divided_floor_counter] ^ 1 << divided_counter_rest;
        }
      }
      counter = -1;
      while (counter < b.length) {
        counter++;
        b[counter] = all_allowed_characters.charAt(b[counter] || 0);
      }
      return b.join("") + "~";
    };

    return FOO;

  })();

  pa = new FOO();

  J = function(a) {
    return pa.set(a);
  };

  is_function = function(a) {
    return typeof a === "function";
  };

  is_object = function(variable) {
    return typeof variable === "object";
  };

  is_boolean = function(variable) {
    return typeof variable === "boolean";
  };

  ka = function(a) {
    return "[object Array]" === Object.prototype.toString.call(Object(a));
  };

  qa = function(a) {
    return 0 !== a && -1 < (a.constructor + "").indexOf("String");
  };

  D = function(a, b) {
    return a.indexOf(b) === 0;
  };

  sa = function(a) {
    if (a) {
      return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g, "");
    } else {
      return "";
    }
  };

  ta = function(a) {
    var b;
    b = document.createElement("img");
    b.width = 1;
    b.height = 1;
    b.src = a;
    return b;
  };

  ua = function() {};

  K = function(a) {
    if (aa instanceof Function) {
      return aa(a);
    }
    J(28);
    return a;
  };

  L = function(a, b, c, d) {
    var e;
    try {
      if (a.addEventListener) {
        return a.addEventListener(b, c, !!d);
      } else {
        return a.attachEvent && a.attachEvent("on" + b, c);
      }
    } catch (_error) {
      e = _error;
      return J(27);
    }
  };

  va = function(a, b, c) {
    if (a.removeEventListener) {
      return a.removeEventListener(b, c, false);
    } else {
      return a.detachEvent && a.detachEvent("on" + b, c);
    }
  };

  wa = function(script_url, element_id) {
    var first_script_element, script_element;
    if (script_url) {
      script_element = document.createElement("script");
      script_element.type = "text/javascript";
      script_element.async = true;
      script_element.src = script_url;
      if (element_id) {
        script_element.id = element_id;
      }
      first_script_element = document.getElementsByTagName("script")[0];
      first_script_element.parentNode.insertBefore(script_element, first_script_element);
    }
  };

  xa = function() {
    var hostname;
    hostname = "" + document.location.hostname;
    if (D(hostname, 'www.')) {
      return hostname.substring(4);
    } else {
      return hostname;
    }
  };

  ya = function(a) {
    var c, referrer;
    referrer = document.referrer;
    if (/^https?:\/\//i.test(referrer)) {
      if (a) {
        return referrer;
      }
      a = "//" + document.location.hostname;
      c = referrer.indexOf(a);
      if (c === 5 || c === 6) {
        a = referrer.charAt(c + a.length);
        if (a === "/" || a === "?" || a === "" || a === ":") {
          return;
        }
      }
      return referrer;
    }
  };

  za = function(a, b) {
    var c, d, e, g;
    if (b.length === 1 && b[0] !== null && is_object(b[0])) {
      return b[0];
    }
    c = {};
    d = Math.min(a.length + 1, b.length);
    e = -1;
    while (e < d) {
      e++;
      if (is_object(b[e])) {
        for (g in b[e]) {
          b[e].hasOwnProperty(g);
          c[g] = b[e][g];
        }
        break;
      } else {
        if (e < a[y]) {
          c[a[e]] = b[e];
        }
      }
    }
    return c;
  };

  N = (function() {
    function N() {

      /*
       */
      this.keys = [];
      this.w = {};
      this.m = {};
    }

    N.prototype.set = function(a, b, c) {

      /*
       */
      this.keys.push(a);
      if (c) {
        return this.m[":" + a] = b;
      } else {
        return this.w[":" + a] = b;
      }
    };

    N.prototype.get = function(a) {

      /*
       */
      if (this.m.hasOwnProperty(":" + a)) {
        return this.m[":" + a];
      } else {
        return this.w[":" + a];
      }
    };

    N.prototype.map = function(a) {

      /*
       */
      var d, k, _i, _len, _ref, _results;
      _ref = this.keys;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        k = _ref[_i];
        d = this.get(k);
        if (d) {
          _results.push(a(c, d));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    return N;

  })();

  O = f;

  M = document;

  fb = function(a) {
    return setTimeout(a, 100);
  };

  Mc = function() {
    var a, b, c, cookie, referrer;
    if (document.cookie) {
      cookie = document.cookie;
    } else {
      cookie = '';
    }
    if (document.referrer) {
      referrer = document.referrer;
    } else {
      referrer = '';
    }
    a = window.navigator.userAgent + cookie + referrer;
    b = a.length;
    c = window.history.length;
    while (c > 0) {
      a += c-- ^ b++;
      c--;
    }
    return La(a);
  };

  Aa = function(a) {
    var d, ga_user_preferences, window_external;
    ga_user_preferences = window._gaUserPrefs;
    if (ga_user_preferences && ga_user_preferences.ioo && ga_user_preferences.ioo() || a && window["ga-disable-" + a] === true) {
      return true;
    }
    try {
      window_external = window.external;
      if (window_external && window_external._gaUserPrefs && "oo" === window_external._gaUserPrefs) {
        return true;
      }
    } catch (_error) {
      d = _error;
    }
    return false;
  };

  Ca = function(a) {
    var b, c, custom_regex, d, e;
    b = [];
    c = document.cookie.split(";");
    custom_regex = new RegExp("^\\s*" + a + "=\\s*(.*?)\\s*$");
    d = 0;
    while (d < c.length) {
      e = c[d].match(custom_regex);
      if (e) {
        b.push(e[1]);
      }
      d++;
    }
    return b;
  };

  zc = function(a, b, c, d, e, g) {
    var foo, gmt_string, _i, _len;
    if (Aa(e)) {
      e = false;
    } else {
      if (eb.test(document.location.hostname) || c === "/" && vc.test(d)) {
        e = false;
      } else {
        e = true;
      }
    }
    if (!e) {
      returnfalse;
    }
    if (b && 1200 < b[y]) {
      b = b.substring(0, 1200);
      J(24);
    }
    c = "" + a + "=" + b + "; path=" + c + ";";
    gmt_string = (new Date((new Date).getTime() + g)).toGMTString();
    if (g) {
      c += "expires=" + gmt_string + "; ";
    }
    if (d && d !== "none") {
      c += "domain=" + d + ";";
    }
    d = document.cookie;
    document.cookie = c;
    d = d !== document.cookie;
    if (!d) {
      t;
    } else {
      a = Ca(a);
      d = 0;
      for (_i = 0, _len = a.length; _i < _len; _i++) {
        foo = a[_i];
        if (b === foo) {
          d = true;
          break;
        }
      }
      d = false;
    }
    return d;
  };

  Cc = function(a) {
    return K(a).replace(/\(/g, "%28").replace(/\)/g, "%29");
  };

  vc = /^(www\.)?google(\.com?)?(\.[a-z]{2})?$/;

  eb = /(^|\.)doubleclick\.net$/i;

  oc = function() {
    var protocol;
    if (Ba || "https:" === document.location.protocol) {
      protocol = "https:";
    } else {
      protocol = "http:";
    }
    return "" + protocol + "//www.google-analytics.com";
  };

  Da = function(a) {
    fa(this, "len");
    return this.message = a + "-8192";
  };

  Ea = function(a) {
    fa(this, "ff2post");
    return this.message = a + "-2036";
  };

  Ga = function(url_string, data, c, d) {
    c = c || ua;
    if (d) {
      d = c;
      if (window.navigator.sendBeacon) {
        if (window.navigator.sendBeacon(url_string, data)) {
          d();
          d = true;
        } else {
          d = false;
        }
      } else {
        d = false;
      }
    }
    if (!d) {
      if (2036 >= data.length) {
        return wc(url_string, data, c);
      } else if (8192 >= data.length) {
        if (0 <= window.navigator.userAgent.indexOf("Firefox") && ![].reduce) {
          throw new Ea(data.length);
        }
        return wd(url_string, data, c) || xd(url_string, data, c) || Fa(data, c) || c();
      } else {
        throw new Da(data.length);
      }
    }
  };

  wc = function(a, b, onload_callback) {
    var d;
    d = ta("" + a + "?" + b);
    return d.onload = d.onerror = function() {
      d.onload = null;
      d.onerror = null;
      return onload_callback();
    };
  };

  xd = function(url_string, data, callback) {
    var cross_domain_request;
    cross_domain_request = window.XDomainRequest;
    if (!cross_domain_request) {
      return false;
    }
    cross_domain_request = new cross_domain_request;
    cross_domain_request.open("POST", url_string);
    cross_domain_request.onerror = function() {
      return callback();
    };
    cross_domain_request.onload = callback;
    cross_domain_request.send(data);
    return true;
  };

  wd = function(url_string, data, callback) {
    var request_sender, xml_http_request;
    xml_http_request = window.XMLHttpRequest;
    if (!xml_http_request) {
      return false;
    }
    request_sender = new xml_http_request;
    if (!(__indexOf.call(request_sender, "withCredentials") >= 0)) {
      return false;
    }
    request_sender.open("POST", url_string, true);
    request_sender.withCredentials = true;
    request_sender.setRequestHeader("Content-Type", "text/plain");
    request_sender.onreadystatechange = function() {
      if (request_sender.readyState === 4) {
        callback();
        return request_sender = null;
      }
    };
    request_sender.send(data);
    return true;
  };

  Fa = function(a, b) {
    var ca, d, e, g, iframe_element, k, l;
    if (!document.body) {
      fb(function() {
        return Fa(a, b);
      });
      return true;
    }
    a = aa(a);
    try {
      iframe_element = document.createElement('<iframe name="' + a + '"></iframe>');
    } catch (_error) {
      d = _error;
      iframe_element = document.createElement("iframe");
      fa(iframe_element, a);
    }
    iframe_element.height = "0";
    iframe_element.width = "0";
    iframe_element.style.display = "none";
    iframe_element.style.visibility = "hidden";
    e = document.location;
    e = oc() + "/analytics_iframe.html#" + encodeURIComponent("" + e.protocol + "//" + e.host + "/favicon.ico");
    g = function() {
      iframe_element.src = "";
      if (iframe_element.parentNode) {
        return iframe_element.parentNode.removeChild(iframe_element);
      }
    };
    L(window, "beforeunload", g);
    ca = false;
    l = 0;
    k = function() {
      if (!ca) {
        try {
          if (9 < l || iframe_element.contentWindow[B][x] === M[B][x]) {
            ca = true;
            g();
            va(O, "beforeunload", g);
            b();
            return;
          }
        } catch (_error) {
          a = _error;
        }
        l++;
        return ba(k, 200);
      }
    };
    L(iframe_element, "load", k);
    document.body.appendChild(iframe_element);
    iframe_element.src = e;
    return true;
  };

  Ha = (function() {
    function Ha() {

      /*
       */
      this.t = [];
    }

    Ha.prototype.add = function(a) {

      /*
       */
      return this.t.push(a);
    };

    Ha.prototype.D = function(a) {

      /*
       */
      var b, c, d, foo_bar, _i, _len, _ref;
      try {
        _ref = this.t;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          foo_bar = _ref[_i];
          c = a.get(foo_bar);
          if (c) {
            is_function(c);
            c.call(window, a);
          }
        }
      } catch (_error) {
        d = _error;
      }
      b = a.get(Ia);
      if (b !== ua) {
        is_function(b);
        a.set(Ia, ua, true);
        return ba(b, 10);
      }
    };

    return Ha;

  })();

  Ja = function(a) {
    if (100 !== a.get(Ka) && La(P(a, Q)) % 10000 >= 100 * R(a, Ka)) {
      throw "abort";
    }
  };

  Ma = function(a) {
    if (Aa(P(a, Na))) {
      throw "abort";
    }
  };

  Oa = function() {
    var protocol;
    protocol = document.location.protocol;
    if (protocol !== "http:" && protocol !== "https:") {
      throw "abort";
    }
  };

  Pa = function(a) {
    var b, c;
    try {
      if (window.XMLHttpRequest) {
        if (__indexOf.call(new window.XMLHttpRequest, "withCredentials") >= 0) {
          J(40);
        } else {
          if (window.XDomainRequest) {
            J(41);
          }
          if (window.navigator.sendBeacon) {
            J(42);
          }
        }
      }
    } catch (_error) {
      b = _error;
    }
    a.set(Ac, R(a, Ac) + 1);
    c = [];
    Qa.map(function(b, e) {
      var g;
      if (e.p) {
        g = a.get(b);
        if (g !== 0 && g !== e.defaultValue) {
          if (is_boolean(g)) {
            g *= 1;
          }
          return c.push(e.p + "=" + K("" + g));
        }
      }
    });
    c.push("z=" + Bd());
    return a.set(Ra, c.join("&"), true);
  };

  Sa = function(a) {
    var b;
    b = P(a, gd) || oc() + "/collect";
    Ga(b, P(a, Ra), a.get(Ia), a.get(Vd));
    return a.set(Ia, ua, true);
  };

  Hc = function(a) {
    var ga_data;
    ga_data = window.gaData;
    if (ga_data) {
      if (ga_data.expId) {
        a.set(Nc, ga_data.expId);
      }
      if (ga_data.expVar) {
        return a.set(Oc, ga_data.expVar);
      }
    }
  };

  cd = function() {
    if (window.navigator && window.navigator.loadPurpose === "preview") {
      throw "abort";
    }
  };

  yd = function(a) {
    var ga_dev_ids;
    ga_dev_ids = window.gaDevIds;
    if (ka(ga_dev_ids) && ga_dev_ids.length !== 0) {
      return a.set("&did", ga_dev_ids.join(","), true);
    }
  };

  vb = function(a) {
    if (!(a.get(Na))) {
      throw "abort";
    }
  };

  hd = function() {
    return Math.round(2147483647 * Math.random());
  };

  Bd = function() {
    var a, b;
    try {
      a = new Uint32Array(1);
      window.crypto.getRandomValues(a);
      return a[0] & 2147483647;
    } catch (_error) {
      b = _error;
      return hd();
    }
  };

  Ta = function(a) {
    var b, c, current_miliseconds, e;
    b = R(a, Ua);
    if (500 <= b) {
      J(15);
    }
    c = P(a, Va);
    if (c !== "transaction" && c !== "item") {
      c = R(a, Wa);
      current_miliseconds = (new Date).getTime();
      e = R(a, Xa);
      if (0 === e) {
        a.set(Xa, current_miliseconds);
      }
      e = Math.round(2 * (current_miliseconds - e) / 1000);
      if (0 < e) {
        c = Math.min(c + e, 20);
        a.set(Xa, current_miliseconds);
      }
      if (0 >= c) {
        throw "abort";
      }
      a.set(Wa, --c);
    }
    return a.set(Ua, ++b);
  };

  Ya = (function() {
    function Ya() {

      /*
       */
      this.data = new N;
    }

    Ya.prototype.get = function(a) {

      /*
       */
      var b, c;
      b = $a(a);
      c = this.data.get(a);
      if (b && 0 === c) {
        if (is_function(b.defaultValue)) {
          c = b.defaultValue();
        } else {
          c = b.defaultValue;
        }
      }
      if (b && b.n) {
        return b.n(this, a, c);
      } else {
        return c;
      }
    };

    Ya.prototype.set = function(a, b, c) {

      /*
       */
      var d, _results;
      if (a) {
        if (is_object(a)) {
          _results = [];
          for (d in a) {
            if (a.hasOwnProperty(d)) {
              _results.push(ab(this, d, a[d], c));
            } else {
              _results.push(void 0);
            }
          }
          return _results;
        } else {
          return ab(this, a, b, c);
        }
      }
    };

    return Ya;

  })();

  Qa = new N;

  Za = [];

  P = function(a, b) {
    var c;
    c = a.get(b);
    if (0 === c) {
      return "";
    } else {
      return "" + c;
    }
  };

  R = function(a, b) {
    var c;
    c = a.get(b);
    if (0 === c || c === '') {
      return 0;
    } else {
      return 1 * c;
    }
  };

  ab = function(a, b, c, d) {
    var e;
    if (c !== 0) {
      switch (false) {
        case b !== Na:
          wb[s](c);
          break;
        default:
          null;
      }
    }
    e = $a(b);
    if (e && e.o) {
      return e.o(a, b, c, d);
    } else {
      return a.data.set(b, c, d);
    }
  };

  bb = function(a, b, c, d, e) {
    fa(this, a);
    this.p = b;
    this.n = d;
    this.o = e;
    return this.defaultValue = c;
  };

  $a = function(a) {
    var b, d, e, _i, _len;
    b = Qa.get(a);
    if (!b) {
      for (_i = 0, _len = Za.length; _i < _len; _i++) {
        d = Za[_i];
        e = d[0].exec(a);
        if (e) {
          b = d[1](e);
          Qa.set(b.name, b);
          break;
        }
      }
    }
    return b;
  };

  yc = function(a) {
    var b;
    b = null;
    Qa.map(function(c, d) {
      if (d.p === a) {
        return b = d;
      }
    });
    return b && b.name;
  };

  S = function(a, b, c, d, e) {
    a = new bb(a, b, c, d, e);
    Qa.set(a.name, a);
    return a.name;
  };

  cb = function(a, b) {
    return Za.push([new RegExp("^" + a + "$"), b]);
  };

  T = function(a, b, c) {
    return S(a, b, c, 0, db);
  };

  db = function() {};

  gb = qa(f.GoogleAnalyticsObject) && sa(f.GoogleAnalyticsObject) || "ga";

  Ba = false;

  hb = T("apiVersion", "v");

  ib = T("clientVersion", "_v");

  S("anonymizeIp", "aip");

  jb = S("adSenseId", "a");

  Va = S("hitType", "t");

  Ia = S("hitCallback");

  Ra = S("hitPayload");

  S("nonInteraction", "ni");

  S("currencyCode", "cu");

  Vd = S("useBeacon", 0, false);

  S("dataSource", "ds");

  S("sessionControl", "sc", "");

  S("sessionGroup", "sg");

  S("queueTime", "qt");

  Ac = S("_s", "_s");

  S("screenName", "cd");

  kb = S("location", "dl", "");

  lb = S("referrer", "dr");

  mb = S("page", "dp", "");

  S("hostname", "dh");

  nb = S("language", "ul");

  ob = S("encoding", "de");

  S("title", "dt", function() {
    return document.title || 0;
  });

  cb("contentGroup([0-9]+)", function(a) {
    return new bb(a[0], "cg" + a[1]);
  });

  pb = S("screenColors", "sd");

  qb = S("screenResolution", "sr");

  rb = S("viewportSize", "vp");

  sb = S("javaEnabled", "je");

  tb = S("flashVersion", "fl");

  S("campaignId", "ci");

  S("campaignName", "cn");

  S("campaignSource", "cs");

  S("campaignMedium", "cm");

  S("campaignKeyword", "ck");

  S("campaignContent", "cc");

  ub = S("eventCategory", "ec");

  xb = S("eventAction", "ea");

  yb = S("eventLabel", "el");

  zb = S("eventValue", "ev");

  Bb = S("socialNetwork", "sn");

  Cb = S("socialAction", "sa");

  Db = S("socialTarget", "st");

  Eb = S("l1", "plt");

  Fb = S("l2", "pdt");

  Gb = S("l3", "dns");

  Hb = S("l4", "rrt");

  Ib = S("l5", "srt");

  Jb = S("l6", "tcp");

  Kb = S("l7", "dit");

  Lb = S("l8", "clt");

  Mb = S("timingCategory", "utc");

  Nb = S("timingVar", "utv");

  Ob = S("timingLabel", "utl");

  Pb = S("timingValue", "utt");

  S("appName", "an");

  S("appVersion", "av", "");

  S("appId", "aid", "");

  S("appInstallerId", "aiid", "");

  S("exDescription", "exd");

  S("exFatal", "exf");

  Nc = S("expId", "xid");

  Oc = S("expVar", "xvar");

  Rc = S("_utma", "_utma");

  Sc = S("_utmz", "_utmz");

  Tc = S("_utmht", "_utmht");

  Ua = S("_hc", 0, 0);

  Xa = S("_ti", 0, 0);

  Wa = S("_to", 0, 20);

  cb("dimension([0-9]+)", function(a) {
    return new bb(a[0], "cd" + a[1]);
  });

  cb("metric([0-9]+)", function(a) {
    return new bb(a[0], "cm" + a[1]);
  });

  S("linkerParam", 0, 0, Bc, db);

  ld = S("usage", "_u", 0, function() {
    return pa.M();
  }, db);

  S("forceSSL", 0, 0, function() {
    return Ba;
  }, function(a, b, c) {
    J(34);
    return Ba = !!c;
  });

  ed = S("_j1", "jid");

  Hd = S("_j2", "gjid");

  cb("\\&(.*)", function(a) {
    var b, c;
    b = new bb(a[0], a[1]);
    c = yc(a[0].substring(1));
    if (c) {
      b.n = function(a) {
        return a.get(c);
      };
      b.o = function(a, b, g, ca) {
        return a.set(c, g, ca);
      };
      b.p = 0;
    }
    return b;
  });

  Qb = T("_oot");

  dd = S("previewTask");

  Rb = S("checkProtocolTask");

  md = S("validationTask");

  Sb = S("checkStorageTask");

  Uc = S("historyImportTask");

  Tb = S("samplerTask");

  Vb = T("_rlt");

  Wb = S("buildHitTask");

  Xb = S("sendHitTask");

  Vc = S("ceTask");

  zd = S("devIdTask");

  Cd = S("timingTask");

  Ld = S("displayFeaturesTask");

  V = T("name");

  Q = T("clientId", "cid");

  Ad = S("userId", "uid");

  Na = T("trackingId", "tid");

  U = T("cookieName", 0, "_ga");

  W = T("cookieDomain");

  Yb = T("cookiePath", 0, "/");

  Zb = T("cookieExpires", 0, 63072000);

  $b = T("legacyCookieDomain");

  Wc = T("legacyHistoryImport", 0, true);

  ac = T("storage", 0, "cookie");

  bc = T("allowLinker", 0, false);

  cc = T("allowAnchor", 0, true);

  Ka = T("sampleRate", "sf", 100);

  dc = T("siteSpeedSampleRate", 0, 1);

  ec = T("alwaysSendReferrer", 0, false);

  gd = S("transportUrl");

  Md = S("_r", "_r");

  X = function(a, b, c, d) {
    return b[a] = function() {
      var ca, g;
      try {
        if (d) {
          J(d);
        }
        return c.apply(this, arguments);
      } catch (_error) {
        b = _error;
        g = b && b.name;
        if (!(1 <= 100 * Math.random() || Aa("?"))) {
          ca = ["t=error", "_e=exc", "_v=j31", "sr=1"];
          if (a) {
            ca.push("_f=" + a);
          }
          if (g) {
            ca.push("_m=" + K(g.substring(0, 100)));
          }
          ca.push("aip=1");
          ca.push("z=" + hd());
          Ga(oc() + "/collect", ca.join("&"));
        }
        throw b;
      }
    };
  };

  Od = function() {
    this.V = 10000;
    this.fa = 0;
    this.$ = false;
    return this.ea = 1;
  };

  Ed = function() {
    var a, b;
    a = new Od;
    if (a.fa && a.$) {
      return 0;
    }
    a.$ = true;
    if (a.V === 0) {
      return 0;
    }
    if (b === 0) {
      b = Bd();
    }
    if (b % a.V === 0) {
      return Math.floor(b / a.V) % a.ea + 1;
    } else {
      return 0;
    }
  };

  fc = function() {
    var a, b, ca, flash_plugin, g, l, navigator, plugin, plugin_counter, plugin_list;
    navigator = window.navigator;
    plugin_list = null;
    if (navigator) {
      plugin_list = navigator.plugins;
    }
    if (plugin_list && plugin_list.length) {
      plugin_counter = 0;
      while (plugin_counter < plugin_list.length && !flash_plugin) {
        plugin = plugin_list[plugin_counter];
        if (-1 < plugin.name.indexOf("Shockwave Flash")) {
          flash_plugin = plugin.description;
        }
        plugin_counter++;
      }
    }
    if (!flash_plugin) {
      try {
        a = new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7");
        b = a.GetVariable("$version");
      } catch (_error) {
        g = _error;
      }
    }
    if (!flash_plugin) {
      try {
        a = new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");
        b = "WIN 6,0,21,0";
        a.AllowScriptAccess = "always";
        b = a.GetVariable("$version");
      } catch (_error) {
        ca = _error;
      }
    }
    if (!flash_plugin) {
      try {
        a = new ActiveXObject("ShockwaveFlash.ShockwaveFlash");
        b = a.GetVariable("$version");
      } catch (_error) {
        l = _error;
      }
    }
    if (flash_plugin) {
      a = flash_plugin.match(/[\d]+/g);
      if (3 <= a.length) {
        flash_plugin = a[0] + "." + a[1] + " r" + a[2];
      }
    }
    return flash_plugin || 0;
  };

  gc = function(a, b) {
    var c, d;
    c = Math.min(R(a, dc), 100);
    if (!(La(P(a, Q)) % 100 >= c)) {
      c = {};
      Ec(c) || Fc(c);
      d = c[Eb];
      if (0 === d || Infinity === d || isNaN(d)) {
        if (0 < d) {
          Y(c, Gb);
          Y(c, Jb);
          Y(c, Ib);
          Y(c, Fb);
          Y(c, Hb);
          Y(c, Kb);
          Y(c, Lb);
          return b(c);
        } else {
          return L(window, "load", function() {
            return gc(a, b);
          }, false);
        }
      }
    }
  };

  Ec = function(a) {
    var navigation_start, performance_timing;
    performance_timing = window.performance || window.webkitPerformance;
    performance_timing = performance_timing && performance_timing.timing;
    if (!performance_timing) {
      return false;
    }
    navigation_start = performance_timing.navigationStart;
    if (navigation_start === 0) {
      return false;
    }
    a[Eb] = performance_timing.loadEventStart - navigation_start;
    a[Gb] = performance_timing.domainLookupEnd - performance_timing.domainLookupStart;
    a[Jb] = performance_timing.connectEnd - performance_timing.connectStart;
    a[Ib] = performance_timing.responseStart - performance_timing.requestStart;
    a[Fb] = performance_timing.responseEnd - performance_timing.responseStart;
    a[Hb] = performance_timing.fetchStart - navigation_start;
    a[Kb] = performance_timing.domInteractive - navigation_start;
    a[Lb] = performance_timing.domContentLoadedEventStart - navigation_start;
    return true;
  };

  Fc = function(a) {
    var external, load_time;
    if (window.top !== window) {
      return false;
    }
    external = window.external;
    load_time = external && external.onloadT;
    if (external) {
      if (!external.isValidLoadTime) {
        load_time = 0;
      }
    }
    if (2147483648 < load_time) {
      load_time = 0;
    }
    if (0 < load_time) {
      external.setPageReadyTime();
    }
    if (load_time === 0) {
      return false;
    }
    a[Eb] = load_time;
    return true;
  };

  Y = function(a, b) {
    var c;
    c = a[b];
    if (isNaN(c) || Infinity === c || c < 0) {
      return a[b] = 0;
    }
  };

  Fd = function(a) {
    return function(b) {
      if (b.get(Va) !== 'pageview' || a.I) {
        a.I = true;
        return gc(b, function(b) {
          return a.send("timing", b);
        });
      }
    };
  };

  hc = false;

  mc = function(a) {
    var b, c, ca, d, e, g, l, __none, _i, _j, _k, _len, _len1, _ref;
    if (P(a, ac) === "cookie") {
      b = P(a, U);
      c = nd(a);
      d = kc(P(a, Yb));
      e = lc(P(a, W));
      g = 1000 * R(a, Zb);
      ca = P(a, Na);
      if (e !== "auto") {
        if (zc(b, c, d, e, ca, g)) {
          return hc = true;
        }
      } else {
        _ref = [1];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          __none = _ref[_i];
          J(32);
          c = [];
          e = xa().split(".");
          l = e[e.length - 1];
          if (4 === e.length && parseInt(l, 10) === l) {
            l = ["none"];
            break;
          }
          for (_j = e.length - 1; _j >= 0; _j += -1) {
            l = e[_j];
            c.push(e.slice(l).join("."));
          }
          c.push("none");
          l = c;
          for (_k = 0, _len1 = l.length; _k < _len1; _k++) {
            e = l[_k];
            a.data.set(W, e);
            c = nd(a);
            if (zc(b, c, d, e, ca, g)) {
              hc = true;
              return;
            }
          }
          a.data.set(W, "auto");
        }
      }
    }
  };

  nc = function(a) {
    if (P(a, ac) === "cookie" && !hc && mc(a)) {
      throw "abort";
    }
  };

  Yc = function(a) {
    var b, c, d;
    if (a.get(Wc)) {
      b = P(a, W);
      c = P(a, $b) || xa();
      d = Xc("__utma", c, b);
      if (d) {
        J(19);
        a.set(Tc, (new Date).getTime(), true);
        a.set(Rc, d.R);
        b = Xc("__utmz", c, b);
        if (d.hash === b.hash) {
          return a.set(Sc, b.R);
        }
      }
    }
  };

  nd = function(a) {
    var b, c;
    b = Cc(P(a, Q));
    c = ic(P(a, W));
    a = jc(P(a, Yb));
    if (1 < a) {
      c += "-" + a;
    }
    return ["GA1", c, b].join(".");
  };

  Gc = function(a, b, c) {
    var d, e, g, l, _i, _len;
    d = [];
    e = [];
    for (_i = 0, _len = a.length; _i < _len; _i++) {
      l = a[_i];
      if (l.r[c] === b) {
        d.push(l);
      } else {
        if (0 === g || l.r[c] < g) {
          e = [l];
          g = l.r[c];
        } else {
          if (l.r[c] === g) {
            e.push(l);
          }
        }
      }
    }
    if (0 < d.length) {
      return d;
    } else {
      return e;
    }
  };

  lc = function(a) {
    if (D(a, '.')) {
      return a.substr(1);
    } else {
      return a;
    }
  };

  ic = function(a) {
    return lc(a).split(".").length;
  };

  kc = function(a) {
    if (!a) {
      return "/";
    }
    if (1 < a.length && a.lastIndexOf("/") === a.length - 1) {
      a = a.substr(0, a.length - 1);
    }
    if (0 !== a.indexOf("/")) {
      a = "/" + a;
    }
    return a;
  };

  jc = function(a) {
    a = kc(a);
    if ("/" === a) {
      return 1;
    } else {
      return a.split("/").length;
    }
  };

  Xc = function(a, b, c) {
    var ca, d, e, val, _i, _len;
    if (b === "none") {
      b = "";
    }
    d = [];
    e = Ca(a);
    if ("__utma" === a) {
      a = 6;
    } else {
      a = 2;
    }
    for (_i = 0, _len = e.length; _i < _len; _i++) {
      val = e[_i];
      ca = ("" + val).split(".");
      if (ca.length >= a) {
        d.push({
          hash: ca[0],
          R: val,
          O: ca
        });
      }
    }
    if (0 === d.length) {
      return 0;
    } else {
      if (1 === d.length) {
        return d[0];
      } else {
        return Zc(b, d) || Zc(c, d) || Zc(null, d) || d[0];
      }
    }
  };

  Zc = function(a, b) {
    var c, d, val, _i, _len;
    if (null === a) {
      c = 1;
      d = 1;
    } else {
      c = La(a);
      if (La(D(a, "."))) {
        d = a.substring(1);
      } else {
        d = "." + a;
      }
    }
    for (_i = 0, _len = b.length; _i < _len; _i++) {
      val = b[_i];
      if (val[h] === c || val[h] === d) {
        return val;
      }
    }
  };

  od = new RegExp(/^https?:\/\/([^\/:]+)/);

  pd = /(.*)([?&#])(?:_ga=[^&#]*)(?:&?)(.*)/;

  Bc = function(a) {
    var b;
    a = a.get(Q);
    b = Ic(a, 0);
    return "_ga=1." + K(b + "." + a);
  };

  Ic = function(a, b) {
    var c, current_time, d, plugin, plugins, _i, _len;
    current_time = new Date;
    c = [a, d.userAgent, current_time.getTimezoneOffset(), current_time.getYear(), current_time.getDate(), current_time.getHours(), current_time.getMinutes() + b];
    d = window.navigator;
    plugins = d.plugins || [];
    for (_i = 0, _len = plugins.length; _i < _len; _i++) {
      plugin = plugins[_i];
      c.push(plugin.description);
    }
    return La(c.join("."));
  };

  Dc = (function() {
    function Dc(a) {

      /*
       */
      J(48);
      this.target = a;
      this.T = false;
    }

    Dc.prototype.Q = function(a, b) {

      /*
       */
      if (a.tagName) {
        if ("a" === a.tagName.toLowerCase()) {
          a.href && Pc(a, qd(this, a.href, b));
          return;
        }
        if ("form" === a.tagName.toLowerCase()) {
          return rd(this, a);
        }
      }
      if ("string" === typeof a) {
        return qd(this, a, b);
      }
    };

    Dc.prototype.S = function(a, b, c) {

      /*
       */
      var d, e, form, _i, _len, _ref, _results;
      d = function(c) {
        var element, w;
        try {
          c = c || window.event;
          element = c.target || c.srcElement;
          d = null;
          c = 100;
          while (element && c > 0) {
            if (element.href && element.nodeName.match(/^a(?:rea)?$/i)) {
              d = element;
              break;
            }
            element = element.parentNode;
            c--;
          }
          d = {};
          if (d.protocol === "http:" || d.protocol === "https:") {
            if (sd(a, d.hostname || "") && d.href) {
              return Pc(d, qd(e, d.href, b));
            }
          }
        } catch (_error) {
          w = _error;
          return J(26);
        }
      };
      e = this;
      if (!this.T) {
        this.T = true;
        L(M, "mousedown", d, false);
        L(M, "touchstart", d, false);
        L(M, "keyup", d, false);
      }
      if (c) {
        c = function(b) {
          var foo_c;
          b = b || window.event;
          b = b.target || b.srcElement;
          if (b.action) {
            foo_c = b.action.match(od);
            if (foo_c) {
              sd(a, foo_c[1]);
              return rd(e, b);
            }
          }
        };
        _ref = document.forms;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          form = _ref[_i];
          _results.push(L(form, "submit", c));
        }
        return _results;
      }
    };

    return Dc;

  })();

  qd = function(a, b, c) {
    var d, e;
    d = pd.exec(b);
    if (d && 3 <= d.length) {
      b = d[1];
      if (d[3]) {
        b += d[2] + d[3];
      } else {
        b += "";
      }
    }
    a = a.target.get("linkerParam");
    e = b.indexOf("?");
    d = b.indexOf("#");
    if (c) {
      if (d === -1) {
        b += '#' + a;
      } else {
        b += '&' + a;
      }
      if (e === -1) {
        c = '?';
      } else {
        c = '&';
      }
      if (d === -1) {
        b = b + (c + a);
      } else {
        b = b.substring(0, d) + c + a + b.substring(d);
      }
    }
    return b;
  };

  rd = function(a, form) {
    var child_nodes, hidden_ga_input, linker_param_value, node, _i, _len;
    if (form && form.action) {
      linker_param_value = a.target.get("linkerParam").split("=")[1];
      if ("get" === form.method.toLowerCase()) {
        child_nodes = form.childNodes || [];
        for (_i = 0, _len = child_nodes.length; _i < _len; _i++) {
          node = child_nodes[_i];
          if ("_ga" === node.name) {
            node.setAttribute("value", linker_param_value);
            return;
          }
        }
        hidden_ga_input = document.createElement("input");
        hidden_ga_input.setAttribute("type", "hidden");
        hidden_ga_input.setAttribute("name", "_ga");
        hidden_ga_input.setAttribute("value", linker_param_value);
        return form.appendChild(hidden_ga_input);
      } else {
        if (form.method.toLowerCase() === "post") {
          return form.action = qd(a, form.action);
        }
      }
    }
  };

  sd = function(a, b) {
    var val, _i, _len;
    if (b === document.location.hostname) {
      return false;
    }
    for (_i = 0, _len = a.length; _i < _len; _i++) {
      val = a[_i];
      if (val instanceof RegExp) {
        if (val.test(b)) {
          return true;
        }
      } else if (0 <= b.indexOf(val)) {
        return true;
      }
    }
    return false;
  };

  Jd = (function() {
    function Jd(a, b, c, d) {

      /*
       */
      this.U = b;
      this.aa = c;
      if (b) {
        b = P(a, V);
        if (b && b !== 't0') {
          if (Wd[s](b)) {
            b = "_gat_" + Cc(P(a, Na));
          } else {
            b = "_gat_" + Cc(b);
          }
        } else {
          b = "_gat";
        }
      }
      this.Y = b;
    }

    return Jd;

  })();

  Rd = function(a, b) {
    var c, d;
    c = b.get(Wb);
    b.set(Wb, function(b) {
      var d;
      Pd(a, b);
      d = c(b);
      Qd(a, b);
      return d;
    });
    d = b.get(Xb);
    return b.set(Xb, function(b) {
      c = d(b);
      Id(a, b);
      return c;
    });
  };

  Pd = function(a, b) {
    if (b.get(a.U)) {
      if ("1" === Ca(a.Y)[0]) {
        return b.set(a.U, "", true);
      } else {
        return b.set(a.U, "" + hd(), true);
      }
    }
  };

  Qd = function(a, b) {
    if (b.get(a.U)) {
      return zc(a.Y, "1", b.get(Yb)(b.get(W), b.get(Na), 600000));
    }
  };

  Id = function(a, b) {
    var c, d, e;
    if (b.get(a.U)) {
      c = new N;
      d = function(a) {
        return c.set($a(a).p, b.get(a));
      };
      d(hb);
      d(ib);
      d(Na);
      d(Q);
      d(a.U);
      d(ld);
      e = a.aa;
      c.map(function(a, b) {
        e += K(a) + "=";
        return e += K("" + b) + "&";
      });
      e += "z=" + hd();
      ta(e);
      return b.set(a.U, "", true);
    }
  };

  Wd = /^gtm\d+$/;

  fd = function(a, b) {
    var c, d;
    c = a.b;
    if (!(c.get("dcLoaded"))) {
      J(29);
      if (window._gaq) {
        J(52);
      }
      b = b || {};
      if (b[U]) {
        d = Cc(b[U]);
      }
      d = new Jd(c, ed, "https://stats.g.doubleclick.net/collect?t=dc&aip=1&", d);
      Rd(d, c);
      return c.set("dcLoaded", true);
    }
  };

  Sd = function(a) {
    var b;
    if (a.get("dcLoaded")) {
      b = false;
    } else {
      if (a.get(ac) !== 'cookie') {
        b = false;
      } else {
        b = true;
      }
    }
    if (b) {
      J(51);
      b = new Jd(a, ed);
      Pd(b, a);
      Qd(b, a);
      if (a.get(b.U)) {
        a.set(Md, 1, true);
        return a.set(gd, oc() + "/r/collect", true);
      }
    }
  };

  Kd = function(a, b) {
    var c, d;
    c = a.b;
    if (!c.get("_rlsaLoaded")) {
      J(38);
      b = b || {};
      if (b[U]) {
        d = Cc(b[U]);
      }
      d = new Jd(c, Hd, "https://www.google.com/ads/ga-audiences?t=sr&aip=1&", d);
      Rd(d, c);
      c.set("_rlsaLoaded", true);
      return tc("displayfeatures", a, b);
    }
  };

  Lc = function() {
    var a;
    window.gaGlobal = window.gaGlobal || {};
    a = window.gaGlobal;
    a.hid = a.hid || hd();
    return a.hid;
  };

  ad = null;

  bd = function(a, b, c) {
    var foo_d_bool, gaso_regex, inpage_parameters, location_hash, window_name;
    if (!ad) {
      location_hash = document.location.hash;
      window_name = window.name;
      gaso_regex = /^#?gaso=([^&]*)/;
      foo_d_bool = location_hash && location_hash.match(gaso_regex) || window_name && window_name.match(gaso_regex);
      if (foo_d_bool) {
        location_hash = location_hash[1];
      } else {
        location_hash = Ca("GASO")[0] || "";
      }
      if (location_hash && location_hash.match(/^(?:!([-0-9a-z.]{1,40})!)?([-.\w]{10,1200})$/i)) {
        zc("GASO", "" + location_hash, c, b, a, 0);
        if (f._udo) {
          f._udo = b;
        }
        if (f._utcp) {
          f._utcp = c;
        }
        a = location_hash[1];
        if (a) {
          inpage_parameters = "prefix=" + a + "&";
        } else {
          inpage_parameters = '';
        }
        wa("https://www.google.com/analytics/web/inpage/pub/inpage.js?" + inpage_parameters + hd(), "_gasojs");
      }
      return ad = true;
    }
  };

  wb = /^(UA|YT|MO|GP)-(\d+)-(\d+)$/;

  pc = (function() {
    function pc(a) {

      /*
       */
      var b, c, d;
      b = (function(_this) {
        return function(a, b_var) {
          return _this.b.data.set(a, b_var);
        };
      })(this);
      c = (function(_this) {
        return function(a, foo_var) {
          b(a, foo_var);
          return _this.filters.add(a);
        };
      })(this);
      d = this;
      this.b = new Ya;
      this.filters = new Ha;
      b(V, a[V]);
      b(Na, sa(a[Na]));
      b(U, a[U]);
      b(W, a[W] || xa());
      b(Yb, a[Yb]);
      b(Zb, a[Zb]);
      b($b, a[$b]);
      b(Wc, a[Wc]);
      b(bc, a[bc]);
      b(cc, a[cc]);
      b(Ka, a[Ka]);
      b(dc, a[dc]);
      b(ec, a[ec]);
      b(ac, a[ac]);
      b(Ad, a[Ad]);
      b(hb, 1);
      b(ib, "j31");
      c(Qb, Ma);
      c(dd, cd);
      c(Rb, Oa);
      c(md, vb);
      c(Sb, nc);
      c(Uc, Yc);
      c(Tb, Ja);
      c(Vb, Ta);
      c(Vc, Hc);
      c(zd, yd);
      c(Ld, Sd);
      c(Wb, Pa);
      c(Xb, Sa);
      c(Cd, Fd(this));
      Jc(this.b, a[Q]);
      Kc(this.b);
      this.b.set(jb, Lc());
      bd(this.b.get(Na), this.b.get(W), this.b.get(Yb));
    }

    pc.prototype.get = function(a) {

      /*
       */
      return this.b.get(a);
    };

    pc.prototype.set = function(a, b) {

      /*
       */
      return this.b.set(a, b);
    };

    pc.prototype.send = function(a) {

      /*
       */
      var b, c;
      if (!(1 > arguments.length)) {
        if (typeof arguments[0] === "string") {
          b = arguments[0];
          c = [].slice.call(arguments, 1);
        } else {
          b = arguments[0] && arguments[0][Va];
          c = arguments;
        }
        if (b) {
          c = za(qc[b] || [], c);
          c[Va] = b;
          this.b.set(c, 0, true);
          this.filters.D(this.b);
          this.b.data.m = {};
          return J(44);
        }
      }
    };

    return pc;

  })();

  Jc = function(a, b) {
    var c, ca, d, e, foo_noop, foo_val, g, location_part, val, _i, _j, _len, _len1, _ref;
    if (P(a, ac) === "cookie") {
      hc = false;
      c = null;
      _ref = [0];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        foo_noop = _ref[_i];
        d = Ca(P(a, U));
        if (d && !(1 > d.length)) {
          c = [];
          for (_j = 0, _len1 = d.length; _j < _len1; _j++) {
            val = d[_j];
            g = val.split(".");
            ca = g.shift();
            if ((ca === "GA1" || ca === "1") && 1 < g.length) {
              ca = g.shift().split("-");
              if (1 === ca.length) {
                ca[1] = "1";
              }
              ca[0] *= 1;
              ca[1] *= 1;
              g = {
                r: ca,
                s: g.join(".")
              };
            } else {
              g = 0;
            }
            if (g) {
              c.push(g);
            }
          }
          if (c.length === 1) {
            J(13);
            c = c[0].s;
            break;
          }
          if (0 === c.length) {
            J(12);
          } else {
            J(14);
            d = ic(P(a, W));
            c = Gc(c, d, 0);
            if (1 === c.length) {
              c = c[0].s;
              break;
            }
            d = jc(P(a, Yb));
            c = Gc(c, d, 1);
            c = c[0] && c[0].s;
            break;
          }
        }
        c = 0;
      }
      if (c) {
        c = P(a, W);
        d = P(a, $b) || xa();
        c = Xc("__utma", d, c);
        if (c === 0) {
          c = 0;
        } else {
          c = c.O[1] + "." + c.O[2];
        }
        if (c) {
          J(10);
        }
      }
      if (c) {
        a.data.set(Q, c);
        hc = true;
      }
    }
    c = a.get(cc);
    if (c) {
      location_part = 'href';
    } else {
      location_part = 'search';
    }
    c = document.location[location_part].match("(?:&|#|\\?)" + K("_ga").replace(/([.*+?^=!:${}()|\[\]\/\\])/g, "\\$1") + "=([^&#]*)");
    if (c && c.length === 2) {
      e = c[1];
    } else {
      e = "";
    }
    if (e) {
      if (a.get(bc)) {
        c = e.indexOf(".");
        if (c === -1) {
          J(22);
        } else {
          d = e.substring(c + 1);
        }
        if ("1" !== e.substring(0, c)) {
          J(22);
        } else {
          c = d.indexOf(".");
          if (c === -1) {
            J(22);
          } else {
            e = d.substring(0, c);
            c = d.substring(c + 1);
            if (e !== Ic(c, 0) && e !== Ic(c, -1) && e !== Ic(c, -2)) {
              J(23);
            } else {
              J(11);
              a.data.set(Q, c);
            }
          }
        }
      }
    } else {
      J(21);
    }
    if (b) {
      J(9);
      a.data.set(Q, K(b));
    }
    if (a.get(Q)) {
      c = window.gaGlobal && window.gaGlobal.vid;
      if (!(c && c.search(/^(?:utma\.)?\d+\.\d+$/) !== -1)) {
        c = 0;
      }
      if (c) {
        J(17);
        a.data.set(Q, c);
      } else {
        J(8);
        foo_val = Math.round((new Date).getTime() / 1000);
        a.data.set(Q, [hd() ^ Mc() & 2147483647, foo_val].join("."));
      }
    }
    return mc(a);
  };

  Kc = function(a) {
    var ca, d, document_element, document_location, e, g, location_hash, navigator, path_name, screen, term_to_check, _i, _len;
    navigator = window.navigator;
    screen = window.screen;
    document_location = document.location;
    a.set(lb, ya(a.get(ec)));
    if (document_location) {
      path_name = document_location.pathname || "";
      if ("/" !== e.charAt(0)) {
        J(31);
        path_name = "/" + path_name;
      }
      a.set(kb, document_location.protocol + "//" + document_location.hostname + path_name + document_location.search);
    }
    if (screen) {
      a.set(qb, screen.width + "x" + screen.height);
    }
    if (screen) {
      a.set(pb, screen.colorDepth + "-bit");
    }
    document_element = document.documentElement;
    e = document.body;
    g = e && e.clientWidth && e.clientHeight;
    ca = [];
    if (document_element && document_element.clientWidth && document_element.clientHeight) {
      if (document.compatMode === "CSS1Compat" || !g) {
        ca = [document_element.clientWidth, document_element.clientHeight];
      } else {
        if (g) {
          ca = [e.clientWidth, e.clientHeight];
        }
      }
    }
    if (0 >= ca[0] || 0 >= ca[1]) {
      document_element = '';
    } else {
      document_element = ca.join("x");
    }
    a.set(rb, c);
    a.set(tb, fc());
    a.set(ob, document.characterSet || document.charset);
    a.set(sb, navigator && "function" === typeof navigator.javaEnabled && navigator.javaEnabled() || false);
    a.set(nb, (b && (b.language || navigator.browserLanguage) || "").toLowerCase());
    location_hash = document.location.hash;
    if (document_location && a.get(cc) && location_hash) {
      location_hash = location_hash.split(/[?&#]+/);
      d = [];
      for (_i = 0, _len = location_hash.length; _i < _len; _i++) {
        term_to_check = location_hash[_i];
        if (D(term_to_check, "utm_id") || D(term_to_check, "utm_campaign") || D(term_to_check, "utm_source") || D(term_to_check, "utm_medium") || D(term_to_check, "utm_term") || D(term_to_check, "utm_content") || D(term_to_check, "gclid") || D(term_to_check, "dclid") || D(term_to_check, "gclsrc")) {
          d.push(term_to_check);
        }
      }
      if (0 < d.length) {
        location_hash = "#" + d.join("&");
        return a.set(kb, a.get(kb) + location_hash);
      }
    }
  };

  qc = {
    pageview: [mb],
    event: [ub, xb, yb, zb],
    social: [Bb, Cb, Db],
    timing: [Mb, Nb, Pb, Ob]
  };

  rc = function(a) {
    if (document.visibilityState === "prerender") {
      return false;
    }
    a();
    return true;
  };

  td = /^(?:(\w+)\.)?(?:(\w+):)?(\w+)$/;

  sc = function(main_function_arguments) {
    var first_arg, search_results, second_arg;
    if (is_function(main_function_arguments[0])) {
      return this.u = main_function_arguments[0];
    } else {
      search_results = td.exec(main_function_arguments[0]);
      if (search_results !== null || 4 === search_results.length) {
        this.c = search_results[1] || "t0";
        this.e = search_results[2] || "";
        this.d = search_results[3];
        this.a = [].slice.call(main_function_arguments, 1);
        if (this.e) {
          this.A = this.d === "create";
          this.i = this.d === "require";
          this.g = this.d === "provide";
          this.ba = this.d === "remove";
        }
        if (this.i) {
          if (this.a.length >= 3) {
            this.X = this.a[1];
            this.W = this.a[2];
          } else {
            if (this.a[1]) {
              if (qa(this.a[1])) {
                this.X = this.a[1];
              } else {
                this.W = this.a[1];
              }
            }
          }
        }
      }
      first_arg = main_function_arguments[1];
      second_arg = main_function_arguments[2];
      if (!this.d) {
        throw "abort";
      }
      if (this.i && (!qa(first_arg) || first_arg === "")) {
        throw "abort";
      }
      if (this.g && (!qa(first_arg) || "" === first_arg || !is_function(second_arg))) {
        throw "abort";
      }
      if (ud(this.c) || ud(this.e)) {
        throw "abort";
      }
      if (this.g && this.c !== "t0") {
        throw "abort";
      }
    }
  };

  ud = function(a) {
    return a.indexOf(".") >= 0 || a.indexOf(":") >= 0;
  };

  Yd = new N;

  $d = new N;

  Zd = {
    ec: 45,
    ecommerce: 46,
    linkid: 47
  };

  tc = function(a, b, c) {
    var d, foo_val;
    if (b === $) {
      J(35);
    } else {
      b.get(V);
    }
    d = Yd.get(a);
    if (!is_function(d)) {
      return false;
    }
    b.plugins_ = b.plugins_ || new N;
    if (b.plugins_.get(a)) {
      return true;
    }
    foo_val = new d(b, c || {});
    b.plugins_.set(a, foo_val);
    return true;
  };

  ae = function(a) {
    var additional_bundle, b_func, ca, d, e, link_element, link_search_string, protocol;
    b_func = function(a) {
      var b, c, _ref, _ref1;
      b = (a.hostname || "").split(":")[0].toLowerCase();
      c = (a.protocol || "").toLowerCase();
      c = a.port || ((_ref = "http:" === c) != null ? _ref : {
        80: (_ref1 = "https:" === c) != null ? _ref1 : {
          443: ""
        }
      });
      a = a.pathname || "";
      if (D(a, "/")) {
        a = "/" + a;
      }
      return [b, "" + c, a];
    };
    link_element = document.createElement("a");
    Pc(link_element, document.location.href);
    protocol = (link_element.protocol || "").toLowerCase();
    d = protocol;
    e = b_func(link_element);
    link_search_string = link_element.search || "";
    if (e[1]) {
      additional_bundle = ":" + e[1];
    } else {
      additional_bundle = '';
    }
    ca = d + "//" + e[0] + additional_bundle;
    if (D(a, "//")) {
      a = d + a;
    } else {
      if (D(a, "/")) {
        a = ca + a;
      } else {
        if (!a || D(a, "?")) {
          a = ca + e[2] + (a || link_search_string);
        } else {
          if (0 > a.split("/")[0].indexOf(":")) {
            a = ca + e[2][F](0, e[2].lastIndexOf("/")) + "/" + a;
          }
        }
      }
    }
    Pc(link_element, a);
    d = b_func(link_element);
    return {
      protocol: protocol,
      host: d[0],
      port: d[1],
      path: d[2],
      G: link_element[ga] || "",
      url: a || ""
    };
  };

  Z = {
    ga: function() {
      return Z.f = [];
    }
  };

  Z.ga();

  Z.D = function(a) {
    var b, _results;
    b = Z.J.apply(Z, arguments);
    b = Z.f.concat(b);
    Z.f = [];
    _results = [];
    while (0 < b.length && !Z.v(b[0]) && !(b.shift() || 0 < Z.f.length)) {
      _results.push(Z.f = Z.f.concat(b));
    }
    return _results;
  };

  Z.J = function(a) {
    var Xd, arg, b, be, ca, d, de, document_location_protocol, e, g, http_port, l, protocol, protocol_from_l, _i, _len, _ref;
    b = [];
    for (_i = 0, _len = arguments.length; _i < _len; _i++) {
      arg = arguments[_i];
      try {
        d = new sc(arg);
        if (d.g) {
          Yd.set(d.a[0], d.a[1]);
        } else {
          if (d.i) {
            e = d;
            g = e.a[0];
            if (!is_function(Yd.get(g)) && !$d.get(g)) {
              Zd.hasOwnProperty(g) && J(Zd[g]);
              ca = e.X;
              if (!ca) {
                if (Zd.hasOwnProperty(g)) {
                  J(39);
                  ca = g + ".js";
                } else {
                  J(43);
                }
              }
              if (ca) {
                if (ca && 0 <= ca.indexOf("/")) {
                  protocol = (_ref = Ba || "https:" === document.location.protocol) != null ? _ref : {
                    "https:": "http:"
                  };
                  ca = "" + protocol + "//www.google-analytics.com/plugins/ua/" + ca;
                }
                l = ae(ca);
                e = 0;
                protocol_from_l = l.protocol;
                document_location_protocol = document.location.protocol;
                if ("https:" === protocol_from_l || protocol_from_l === document_location_protocol) {
                  e = true;
                } else {
                  if ("http:" !== protocol_from_l) {
                    e = false;
                  } else {
                    e = "http:" === document_location_protocol;
                  }
                }
                Xd = e;
                if (Xd) {
                  e = l;
                  be = ae(document.location.href);
                  if (e.G || 0 <= e.url.indexOf("?") || 0 <= e.path.indexOf("://")) {
                    Xd = false;
                  } else if (e.host === be.host && e.port === be.port) {
                    Xd = true;
                  } else {
                    if (e.protocol) {
                      http_port = 80;
                    } else {
                      http_port = 443;
                    }
                    if ("www.google-analytics.com" === e.host && (e.port || http_port) === http_port && D(e.path, "/plugins/")) {
                      Xd = true;
                    } else {
                      Xd = false;
                    }
                  }
                }
                if (Xd) {
                  wa(l.url);
                  $d.set(g, true);
                }
              }
            }
          }
          b.push(d);
        }
      } catch (_error) {
        de = _error;
      }
    }
    return b;
  };

  Z.v = function(a) {
    var b, c, d, e, g;
    try {
      if (a.u) {
        return a.u.call(window, $.j("t0"));
      } else {
        if (gb === a.c) {
          b = $;
        } else {
          b = $.j(a.c);
        }
        if (a.A) {
          if (a.c === 't0') {
            return $.create.apply($, a.a);
          }
        } else if (a.ba) {
          return $.remove(a.c);
        } else if (b) {
          if (a.i) {
            if (!tc(a.a[0], b, a.W)) {
              return true;
            }
          }
        } else if (a.e) {
          c = a.d;
          d = a.a;
          e = b.plugins_.get(a.e);
          return e[c].apply(e, d);
        } else {
          return b[a.d].apply(b, a.a);
        }
      }
    } catch (_error) {
      g = _error;
    }
  };

  $ = function(a) {
    J(1);
    return Z.D.apply(Z, [arguments]);
  };

  $.h = {};

  $.P = [];

  $.L = 0;

  $.answer = 42;

  uc = [Na, W, V];

  $.create = function(a) {
    var b, c;
    b = za(uc, [].slice.call(arguments));
    if (b[V]) {
      b[V] = "t0";
    }
    c = "" + b[V];
    if ($.h[c]) {
      return $.h[c];
    }
    b = new pc(b);
    $.h[c] = b;
    $.P[p](b);
    return b;
  };

  $.remove = function(a) {
    var val, _i, _len, _ref, _results;
    _ref = $.P;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      val = _ref[_i];
      if (val.get(V) === a) {
        $.P.splice(b, 1);
        $.h[a] = null;
        break;
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  };

  $.j = function(a) {
    return $.h[a];
  };

  $.K = function() {
    return $.P.slice(0);
  };

  $.N = function() {
    var a, b, c, d;
    if ("ga" !== gb) {
      J(49);
    }
    a = window[gb];
    if (!a || a.answer !== 42) {
      $.L = a && a.l;
      $.loaded = true;
      b = window[gb] = $;
      X("create", b, b.create, 3);
      X("remove", b, b.remove);
      X("getByName", b, b.j, 5);
      X("getAll", b, b.K, 6);
      b = pc.prototype;
      X("get", b, b.get, 7);
      X("set", b, b.set, 4);
      X("send", b, b.send, 2);
      b = Ya.prototype;
      X("get", b, b.get);
      X("set", b, b.set);
      b = document.getElementsByTagName("script");
      c = 0;
      while (c < b.length && c < 100) {
        d = b[c].src;
        if (d) {
          if (d.indexOf("https://www.google-analytics.com/analytics") !== 0) {
            d = false;
          } else {
            d = true;
          }
        } else {
          d = false;
        }
        if (d) {
          J(33);
        }
        c++;
      }
      if ("https:" !== M[B][E] && !Ba && Ed()) {
        J(36);
        Ba = true;
      }
      window.gaplugins = window.gaplugins || {};
      window.gaplugins.Linker = Dc;
      b = Dc.prototype;
      Yd.set("linker", Dc);
      X("decorate", b, b.Q, 20);
      X("autoLink", b, b.S, 25);
      Yd.set("displayfeatures", fd);
      Yd.set("adfeatures", Kd);
      a = a && a.q;
      if (ka(a)) {
        return Z.D.apply($, a);
      } else {
        return J(50);
      }
    }
  };

  $.k = function() {
    var a, val, _i, _len, _results;
    a = $.K();
    _results = [];
    for (_i = 0, _len = a.length; _i < _len; _i++) {
      val = a[_i];
      _results.push(val.get(V));
    }
    return _results;
  };

  ano = function() {
    var a, b, c;
    a = $.N;
    if (!rc(a)) {
      J(16);
      b = false;
      c = function() {
        if (!b && rc(a)) {
          b = true;
          return va(M, "visibilitychange", c);
        }
      };
      return L(M, "visibilitychange", c);
    }
  };

  ano();

  La = function(used_string) {
    var char_position, character, return_char;
    return_char = 1;
    character = 0;
    if (used_string) {
      return_char = 0;
      char_position = used_string.length - 1;
      while (char_position >= 0) {
        character = used_string.charCodeAt(char_position);
        return_char = (return_char << 6 & 268435455) + character + (character << 14);
        character = return_char & 266338304;
        if (character !== 0) {
          return_char = return_char ^ character >> 21;
        }
        char_position--;
      }
    }
    return return_char;
  };

}).call(this);

//# sourceMappingURL=refactoring.js.map
