// Generated by CoffeeScript 1.8.0
(function() {
  var A, Ab, B, C, E, F, FOO, G, H, I, J, Pc, Qc, Ub, aa, ba, da, ea, f, fa, ga, h, ha, ia, id, ja, jd, kd, la, m, ma, n, na, oa, p, pa, q, r, ra, s, t, u, v, x, xc, y, z;

  aa = encodeURIComponent;

  f = window;

  ba = setTimeout;

  n = Math;

  Pc = function(a, b) {
    return a.href = b;
  };

  fa = function(a, b) {
    return a.name = b;
  };

  Qc = "replace";

  q = "data";

  m = "match";

  xc = "send";

  ja = "port";

  u = "createElement";

  id = "setAttribute";

  da = "getTime";

  x = "host";

  A = "split";

  B = "location";

  ra = "hasOwnProperty";

  ma = "hostname";

  ga = "search";

  E = "protocol";

  Ab = "href";

  kd = "action";

  G = "apply";

  p = "push";

  h = "hash";

  s = "test";

  ha = "slice";

  r = "cookie";

  t = "indexOf";

  ia = "defaultValue";

  v = "name";

  y = "length";

  z = "prototype";

  la = "clientWidth";

  jd = "target";

  C = "call";

  na = "clientHeight";

  F = "substring";

  oa = "navigator";

  Ub = "parentNode";

  H = "join";

  I = "toLowerCase";

  FOO = (function() {
    FOO.prototype.a = [];

    function FOO() {

      /*
       */
    }

    FOO.prototype.set = function(b) {

      /*
       */
      return a[b] = !0;
    };

    FOO.prototype.M = function() {

      /*
       */
      var b, c;
      b = [];
      c = 0;
      while (c < a[y]) {
        c++;
        a[c] && (b[n.floor(c / 6)] = b[n.floor(c / 6)] ^ 1 << c % 6);
      }
      c = 0;
      while (c < b[y]) {
        c++;
        b[c] = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_".charAt(b[c] || 0);
      }
      return b[H]("") + "~";
    };

    return FOO;

  })();

  pa = new FOO();

  J = function(a) {
    return pa.set(a);
  };

  ea = function(a) {
    return typeof a === "function";
  };

}).call(this);

//# sourceMappingURL=refactoring.js.map
