// Generated by CoffeeScript 1.8.0
(function() {
  var $a, $b, A, Aa, Ab, Ac, Ad, B, Ba, Bb, Bd, C, Ca, Cb, Cc, Cd, D, Da, Db, E, Ea, Eb, Ec, Ed, F, FOO, Fa, Fb, Fc, Fd, G, Ga, Gb, Gc, H, Ha, Hb, Hc, Hd, I, Ia, Ib, J, Ja, Jb, K, Ka, Kb, L, Lb, Ld, M, Ma, Mb, Mc, Md, N, Na, Nb, Nc, O, Oa, Ob, Oc, Od, P, Pa, Pb, Pc, Q, Qa, Qb, Qc, R, Ra, Rb, Rc, S, Sa, Sb, Sc, T, Ta, Tb, Tc, U, Ua, Ub, Uc, V, Va, Vb, Vc, Vd, W, Wa, Wb, Wc, X, Xa, Xb, Y, Ya, Yb, Yc, Za, Zb, aa, ab, ac, ba, bb, bc, cb, cc, cd, da, db, dc, dd, ea, eb, ec, ed, f, fa, fb, fc, ga, gb, gc, gd, h, ha, hb, hc, hd, ia, ib, id, is_boolean, is_object, ja, jb, jd, ka, kb, kd, la, lb, ld, m, ma, mb, mc, md, n, na, nb, nc, nd, oa, ob, oc, p, pa, pb, q, qa, qb, r, ra, rb, s, sa, sb, t, ta, tb, u, ua, ub, v, va, vb, vc, wa, wc, wd, x, xa, xb, xc, xd, y, ya, yb, yc, yd, z, za, zb, zc, zd,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  aa = encodeURIComponent;

  f = window;

  ba = setTimeout;

  n = Math;

  Pc = function(a, b) {
    return a.href = b;
  };

  fa = function(a, b) {
    return a.name = b;
  };

  Qc = "replace";

  q = "data";

  m = "match";

  xc = "send";

  ja = "port";

  u = "createElement";

  id = "setAttribute";

  da = "getTime";

  x = "host";

  A = "split";

  B = "location";

  ra = "hasOwnProperty";

  ma = "hostname";

  ga = "search";

  E = "protocol";

  Ab = "href";

  kd = "action";

  G = "apply";

  p = "push";

  h = "hash";

  s = "test";

  ha = "slice";

  r = "cookie";

  t = "indexOf";

  ia = "defaultValue";

  v = "name";

  y = "length";

  z = "prototype";

  la = "clientWidth";

  jd = "target";

  C = "call";

  na = "clientHeight";

  F = "substring";

  oa = "navigator";

  Ub = "parentNode";

  H = "join";

  I = "toLowerCase";

  FOO = (function() {
    function FOO() {

      /*
       */
      this.a = [];
    }

    FOO.prototype.set = function(b) {

      /*
       */
      return this.a[b] = !0;
    };

    FOO.prototype.M = function() {

      /*
       */
      var b, c;
      b = [];
      c = -1;
      while (c < a.length) {
        c++;
        this.a[c] && (b[n.floor(c / 6)] = b[n.floor(c / 6)] ^ 1 << c % 6);
      }
      c = -1;
      while (c < b.length) {
        c++;
        b[c] = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_".charAt(b[c] || 0);
      }
      return b.join("") + "~";
    };

    return FOO;

  })();

  pa = new FOO();

  J = function(a) {
    return pa.set(a);
  };

  ea = function(a) {
    return typeof a === "function";
  };

  is_object = function(variable) {
    return typeof variable === "object";
  };

  is_boolean = function(variable) {
    return typeof variable === "boolean";
  };

  ka = function(a) {
    return "[object Array]" === Object.prototype.toString.call(Object(a));
  };

  qa = function(a) {
    return 0 !== a && -1 < (a.constructor + "").indexOf("String");
  };

  D = function(a, b) {
    return 0 === a.indexOf(b);
  };

  sa = function(a) {
    if (a) {
      return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g, "");
    } else {
      return "";
    }
  };

  ta = function(a) {
    var b;
    b = M.createElement("img");
    b.width = 1;
    b.height = 1;
    b.src = a;
    return b;
  };

  ua = function() {};

  K = function(a) {
    if (aa instanceof Function) {
      return aa(a);
    }
    J(28);
    return a;
  };

  L = function(a, b, c, d) {
    var e;
    try {
      if (a.addEventListener) {
        return a.addEventListener(b, c, !!d);
      } else {
        return a.attachEvent && a.attachEvent("on" + b, c);
      }
    } catch (_error) {
      e = _error;
      return J(27);
    }
  };

  va = function(a, b, c) {
    if (a.removeEventListener) {
      return a.removeEventListener(b, c, !1);
    } else {
      return a.detachEvent && a.detachEvent("on" + b, c);
    }
  };

  wa = function(a, b) {
    var c, d;
    if (a) {
      c = M.createElement("script");
      c.type = "text/javascript";
      c.async = !0;
      c.src = a;
      if (b) {
        c.id = b;
      }
      d = M.getElementsByTagName("script")[0];
      d.parentNode.insertBefore(c, d);
    }
  };

  xa = function() {
    var a;
    a = "" + M.location.hostname;
    if (0 === a.indexOf("www.")) {
      return a.substring(4);
    } else {
      return retunr(a);
    }
  };

  ya = function(a) {
    var b, c;
    b = M.referrer;
    if (/^https?:\/\//i.test(b)) {
      if (a) {
        return b;
      }
      a = "//" + M.location.hostname;
      c = b.indexOf(a);
      if (5 === c || 6 === c) {
        a = b.charAt(c + a.length);
        if ("/" === a || "?" === a || "" === a || ":" === a) {
          return;
        }
      }
      return b;
    }
  };

  za = function(a, b) {
    var c, d, e, g;
    if (1 === b[y] && null !== b[0] && is_object(b[0])) {
      return b[0];
    }
    c = {};
    d = n.min(a[y] + 1, b[y]);
    e = -1;
    while (e < d) {
      e++;
      if (is_object(b[e])) {
        for (g in b[e]) {
          b[e][ra](g);
          c[g] = b[e][g];
        }
        break;
      } else {
        if (e < a[y]) {
          c[a[e]] = b[e];
        }
      }
    }
    return c;
  };

  N = (function() {
    function N() {

      /*
       */
      this.keys = [];
      this.w = {};
      this.m = {};
    }

    N.prototype.set = function(a, b, c) {

      /*
       */
      this.keys.push(a);
      if (c) {
        return this.m[":" + a] = b;
      } else {
        return this.w[":" + a] = b;
      }
    };

    N.prototype.get = function(a) {

      /*
       */
      if (this.m.hasOwnProperty(":" + a)) {
        return this.m[":" + a];
      } else {
        return this.w[":" + a];
      }
    };

    N.prototype.map = function(a) {

      /*
       */
      var d, k, _i, _len, _ref, _results;
      _ref = this.keys;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        k = _ref[_i];
        d = this.get(k);
        if (d) {
          _results.push(a(c, d));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    return N;

  })();

  O = f;

  M = document;

  fb = function(a) {
    return setTimeout(a, 100);
  };

  Mc = function() {
    var a, b, c, cookie, referrer;
    if (document.cookie) {
      cookie = document.cookie;
    } else {
      cookie = '';
    }
    if (M.referrer) {
      referrer = M.referrer;
    } else {
      referrer = '';
    }
    a = window.navigator.userAgent + cookie + referrer;
    b = a.length;
    c = window.history.length;
    while (c > 0) {
      a += c-- ^ b++;
      c--;
    }
    return La(a);
  };

  Aa = function(a) {
    var b, c, d;
    b = window._gaUserPrefs;
    if (b && b.ioo && b.ioo() || a && window["ga-disable-" + a] === !0) {
      return !0;
    }
    try {
      c = window.external;
      if (c && c._gaUserPrefs && "oo" === c._gaUserPrefs) {
        return !0;
      }
    } catch (_error) {
      d = _error;
    }
    return !1;
  };

  Ca = function(a) {
    var b, c, custom_regex, d, e;
    b = [];
    c = M.cookie.split(";");
    custom_regex = new RegExp("^\\s*" + a + "=\\s*(.*?)\\s*$");
    d = 0;
    while (d < c.length) {
      e = c[d].match(custom_regex);
      if (e) {
        b.push(e[1]);
      }
      d++;
    }
    return b;
  };

  zc = function(a, b, c, d, e, g) {
    var foo, gmt_string, _i, _len;
    if (Aa(e)) {
      e = !1;
    } else {
      if (eb.test(M.location.hostname) || c === "/" && vc.test(d)) {
        e = !1;
      } else {
        e = !0;
      }
    }
    if (!e) {
      return !1;
    }
    if (b && 1200 < b[y]) {
      b = b.substring(0, 1200);
      J(24);
    }
    c = "" + a + "=" + b + "; path=" + c + ";";
    gmt_string = (new Date((new Date).getTime() + g)).toGMTString();
    if (g) {
      c += "expires=" + gmt_string + "; ";
    }
    if (d && d !== "none") {
      c += "domain=" + d + ";";
    }
    d = M.cookie;
    M.cookie = c;
    d = d !== M.cookie;
    if (!d) {
      t;
    } else {
      a = Ca(a);
      d = 0;
      for (_i = 0, _len = a.length; _i < _len; _i++) {
        foo = a[_i];
        if (b === foo) {
          d = !0;
          break;
        }
      }
      d = !1;
    }
    return d;
  };

  Cc = function(a) {
    return K(a).replace(/\(/g, "%28").replace(/\)/g, "%29");
  };

  vc = /^(www\.)?google(\.com?)?(\.[a-z]{2})?$/;

  eb = /(^|\.)doubleclick\.net$/i;

  oc = function() {
    var protocol;
    if (Ba || "https:" === M.location.protocol) {
      protocol = "https:";
    } else {
      protocol = "http:";
    }
    return "" + protocol + "//www.google-analytics.com";
  };

  Da = function(a) {
    fa(this, "len");
    return this.message = a + "-8192";
  };

  Ea = function(a) {
    fa(this, "ff2post");
    return this.message = a + "-2036";
  };

  Ga = function(a, b, c, d) {
    c = c || ua;
    if (d) {
      d = c;
      if (window.navigator.sendBeacon) {
        if (window.navigator.sendBeacon(a, b)) {
          d();
          d = !0;
        } else {
          d = !1;
        }
      } else {
        d = !1;
      }
    }
    if (!d) {
      if (2036 >= b.length) {
        return wc(a, b, c);
      } else if (8192 >= b.length) {
        if (0 <= window.navigator.userAgent[t]("Firefox") && ![].reduce) {
          throw new Ea(b.length);
        }
        return wd(a, b, c) || xd(a, b, c) || Fa(b, c) || c();
      } else {
        throw new Da(b.length);
      }
    }
  };

  wc = function(a, b, c) {
    var d;
    d = ta("" + a + "?" + b);
    return d.onload = d.onerror = function() {
      d.onload = null;
      d.onerror = null;
      return c();
    };
  };

  xd = function(a, b, c) {
    var d;
    d = window.XDomainRequest;
    if (!d) {
      return !1;
    }
    d = new d;
    d.open("POST", a);
    d.onerror = function() {
      return c();
    };
    d.onload = c;
    d.send(b);
    return !0;
  };

  wd = function(a, b, c) {
    var d, e;
    d = O.XMLHttpRequest;
    if (!d) {
      return !1;
    }
    e = new d;
    if (!(__indexOf.call(e, "withCredentials") >= 0)) {
      return !1;
    }
    e.open("POST", a, !0);
    e.withCredentials = !0;
    e.setRequestHeader("Content-Type", "text/plain");
    e.onreadystatechange = function() {
      if (e.readyState === 4) {
        c();
        return e = null;
      }
    };
    e.send(b);
    return !0;
  };

  Fa = function(a, b) {
    var c, ca, d, e, g, k, l;
    if (!M.body) {
      fb(function() {
        return Fa(a, b);
      });
      return !0;
    }
    a = aa(a);
    try {
      c = M.createElement('<iframe name="' + a + '"></iframe>');
    } catch (_error) {
      d = _error;
      c = M.createElement("iframe");
      fa(c, a);
    }
    c.height = "0";
    c.width = "0";
    c.style.display = "none";
    c.style.visibility = "hidden";
    e = M.location;
    e = oc() + "/analytics_iframe.html#" + encodeURIComponent("" + e.protocol + "//" + e.host + "/favicon.ico");
    g = function() {
      c.src = "";
      if (c.parentNode) {
        return c.parentNode.removeChild(c);
      }
    };
    L(window, "beforeunload", g);
    ca = !1;
    l = 0;
    k = function() {
      if (!ca) {
        try {
          if (9 < l || c.contentWindow[B][x] === M[B][x]) {
            ca = !0;
            g();
            va(O, "beforeunload", g);
            b();
            return;
          }
        } catch (_error) {
          a = _error;
        }
        l++;
        return ba(k, 200);
      }
    };
    L(c, "load", k);
    M.body.appendChild(c);
    c.src = e;
    return !0;
  };

  Ha = (function() {
    function Ha() {

      /*
       */
      this.t = [];
    }

    Ha.prototype.add = function(a) {

      /*
       */
      return this.t.push(a);
    };

    Ha.prototype.D = function(a) {

      /*
       */
      var b, c, d, foo_bar, _i, _len, _ref;
      try {
        _ref = this.t;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          foo_bar = _ref[_i];
          c = a.get(foo_bar);
          if (c) {
            ea(c);
            c.call(window, a);
          }
        }
      } catch (_error) {
        d = _error;
      }
      b = a.get(Ia);
      if (b !== ua) {
        ea(b);
        a.set(Ia, ua, !0);
        return ba(b, 10);
      }
    };

    return Ha;

  })();

  Ja = function(a) {
    if (100 !== a.get(Ka) && La(P(a, Q)) % 10000 >= 100 * R(a, Ka)) {
      throw "abort";
    }
  };

  Ma = function(a) {
    if (Aa(P(a, Na))) {
      throw "abort";
    }
  };

  Oa = function() {
    var a;
    a = M.location.protocol;
    if (a !== "http:" && a !== "https:") {
      throw "abort";
    }
  };

  Pa = function(a) {
    var b, c;
    try {
      if (window.XMLHttpRequest) {
        if (__indexOf.call(new O.XMLHttpRequest, "withCredentials") >= 0) {
          J(40);
        } else {
          if (window.XDomainRequest) {
            J(41);
          }
          if (window.navigator.sendBeacon) {
            J(42);
          }
        }
      }
    } catch (_error) {
      b = _error;
    }
    a.set(Ac, R(a, Ac) + 1);
    c = [];
    Qa.map(function(b, e) {
      var g;
      if (e.p) {
        g = a.get(b);
        if (g !== 0 && g !== e.defaultValue) {
          if (is_boolean(g)) {
            g *= 1;
          }
          return c.push(e.p + "=" + K("" + g));
        }
      }
    });
    c.push("z=" + Bd());
    return a.set(Ra, c.join("&"), !0);
  };

  Sa = function(a) {
    var b;
    b = P(a, gd) || oc() + "/collect";
    Ga(b, P(a, Ra), a.get(Ia), a.get(Vd));
    return a.set(Ia, ua, !0);
  };

  Hc = function(a) {
    var b;
    b = window.gaData;
    if (b) {
      if (b.expId) {
        a.set(Nc, b.expId);
      }
      if (b.expVar) {
        return a.set(Oc, b.expVar);
      }
    }
  };

  cd = function() {
    if (window.navigator && "preview" === window.navigator.loadPurpose) {
      throw "abort";
    }
  };

  yd = function(a) {
    var b;
    b = window.gaDevIds;
    if (ka(b) && b.length !== 0) {
      return a.set("&did", b.join(","), !0);
    }
  };

  vb = function(a) {
    if (!(a.get(Na))) {
      throw "abort";
    }
  };

  hd = function() {
    return Math.round(2147483647 * Math.random());
  };

  Bd = function() {
    var a, b;
    try {
      a = new Uint32Array(1);
      window.crypto.getRandomValues(a);
      return a[0] & 2147483647;
    } catch (_error) {
      b = _error;
      return hd();
    }
  };

  Ta = function(a) {
    var b, c, d, e;
    b = R(a, Ua);
    if (500 <= b) {
      J(15);
    }
    c = P(a, Va);
    if ("transaction" !== c && "item" !== c) {
      c = R(a, Wa);
      d = (new Date).getTime();
      e = R(a, Xa);
      if (0 === e) {
        a.set(Xa, d);
      }
      e = n.round(2 * (d - e) / 1000);
      if (0 < e) {
        c = n.min(c + e, 20);
        a.set(Xa, d);
      }
      if (0 >= c) {
        throw "abort";
      }
      a.set(Wa, --c);
    }
    return a.set(Ua, ++b);
  };

  Ya = (function() {
    function Ya() {

      /*
       */
      this.data = new N;
    }

    Ya.prototype.get = function(a) {

      /*
       */
      var b, c;
      b = $a(a);
      c = this.data.get(a);
      if (b && 0 === c) {
        if (ea(b.defaultValue)) {
          c = b.defaultValue();
        } else {
          c = b.defaultValue;
        }
      }
      if (b && b.n) {
        return b.n(this, a, c);
      } else {
        return c;
      }
    };

    Ya.prototype.set = function(a, b, c) {

      /*
       */
      var d, _results;
      if (a) {
        if (is_object(a)) {
          _results = [];
          for (d in a) {
            if (a.hasOwnProperty(d)) {
              _results.push(ab(this, d, a[d], c));
            } else {
              _results.push(void 0);
            }
          }
          return _results;
        } else {
          return ab(this, a, b, c);
        }
      }
    };

    return Ya;

  })();

  Qa = new N;

  Za = [];

  P = function(a, b) {
    var c;
    c = a.get(b);
    if (0 === c) {
      return "";
    } else {
      return "" + c;
    }
  };

  R = function(a, b) {
    var c;
    c = a.get(b);
    if (0 === c || c === '') {
      return 0;
    } else {
      return 1 * c;
    }
  };

  ab = function(a, b, c, d) {
    var e;
    if (c !== 0) {
      switch (false) {
        case b !== Na:
          wb[s](c);
          break;
        default:
          null;
      }
    }
    e = $a(b);
    if (e && e.o) {
      return e.o(a, b, c, d);
    } else {
      return a.data.set(b, c, d);
    }
  };

  bb = function(a, b, c, d, e) {
    fa(this, a);
    this.p = b;
    this.n = d;
    this.o = e;
    return this.defaultValue = c;
  };

  $a = function(a) {
    var b, d, e, _i, _len;
    b = Qa.get(a);
    if (!b) {
      for (_i = 0, _len = Za.length; _i < _len; _i++) {
        d = Za[_i];
        e = d[0].exec(a);
        if (e) {
          b = d[1](e);
          Qa.set(b.name, b);
          break;
        }
      }
    }
    return b;
  };

  yc = function(a) {
    var b;
    b = null;
    Qa.map(function(c, d) {
      if (d.p === a) {
        return b = d;
      }
    });
    return b && b.name;
  };

  S = function(a, b, c, d, e) {
    a = new bb(a, b, c, d, e);
    Qa.set(a.name, a);
    return a.name;
  };

  cb = function(a, b) {
    return Za.push([new RegExp("^" + a + "$"), b]);
  };

  T = function(a, b, c) {
    return S(a, b, c, 0, db);
  };

  db = function() {};

  gb = qa(f.GoogleAnalyticsObject) && sa(f.GoogleAnalyticsObject) || "ga";

  Ba = !1;

  hb = T("apiVersion", "v");

  ib = T("clientVersion", "_v");

  S("anonymizeIp", "aip");

  jb = S("adSenseId", "a");

  Va = S("hitType", "t");

  Ia = S("hitCallback");

  Ra = S("hitPayload");

  S("nonInteraction", "ni");

  S("currencyCode", "cu");

  Vd = S("useBeacon", 0, !1);

  S("dataSource", "ds");

  S("sessionControl", "sc", "");

  S("sessionGroup", "sg");

  S("queueTime", "qt");

  Ac = S("_s", "_s");

  S("screenName", "cd");

  kb = S("location", "dl", "");

  lb = S("referrer", "dr");

  mb = S("page", "dp", "");

  S("hostname", "dh");

  nb = S("language", "ul");

  ob = S("encoding", "de");

  S("title", "dt", function() {
    return M.title || 0;
  });

  cb("contentGroup([0-9]+)", function(a) {
    return new bb(a[0], "cg" + a[1]);
  });

  pb = S("screenColors", "sd");

  qb = S("screenResolution", "sr");

  rb = S("viewportSize", "vp");

  sb = S("javaEnabled", "je");

  tb = S("flashVersion", "fl");

  S("campaignId", "ci");

  S("campaignName", "cn");

  S("campaignSource", "cs");

  S("campaignMedium", "cm");

  S("campaignKeyword", "ck");

  S("campaignContent", "cc");

  ub = S("eventCategory", "ec");

  xb = S("eventAction", "ea");

  yb = S("eventLabel", "el");

  zb = S("eventValue", "ev");

  Bb = S("socialNetwork", "sn");

  Cb = S("socialAction", "sa");

  Db = S("socialTarget", "st");

  Eb = S("l1", "plt");

  Fb = S("l2", "pdt");

  Gb = S("l3", "dns");

  Hb = S("l4", "rrt");

  Ib = S("l5", "srt");

  Jb = S("l6", "tcp");

  Kb = S("l7", "dit");

  Lb = S("l8", "clt");

  Mb = S("timingCategory", "utc");

  Nb = S("timingVar", "utv");

  Ob = S("timingLabel", "utl");

  Pb = S("timingValue", "utt");

  S("appName", "an");

  S("appVersion", "av", "");

  S("appId", "aid", "");

  S("appInstallerId", "aiid", "");

  S("exDescription", "exd");

  S("exFatal", "exf");

  Nc = S("expId", "xid");

  Oc = S("expVar", "xvar");

  Rc = S("_utma", "_utma");

  Sc = S("_utmz", "_utmz");

  Tc = S("_utmht", "_utmht");

  Ua = S("_hc", 0, 0);

  Xa = S("_ti", 0, 0);

  Wa = S("_to", 0, 20);

  cb("dimension([0-9]+)", function(a) {
    return new bb(a[0], "cd" + a[1]);
  });

  cb("metric([0-9]+)", function(a) {
    return new bb(a[0], "cm" + a[1]);
  });

  S("linkerParam", 0, 0, Bc, db);

  ld = S("usage", "_u", 0, function() {
    return pa.M();
  }, db);

  S("forceSSL", 0, 0, function() {
    return Ba;
  }, function(a, b, c) {
    J(34);
    return Ba = !!c;
  });

  ed = S("_j1", "jid");

  Hd = S("_j2", "gjid");

  cb("\\&(.*)", function(a) {
    var b, c;
    b = new bb(a[0], a[1]);
    c = yc(a[0].substring(1));
    if (c) {
      b.n = function(a) {
        return a.get(c);
      };
      b.o = function(a, b, g, ca) {
        return a.set(c, g, ca);
      };
      b.p = 0;
    }
    return b;
  });

  Qb = T("_oot");

  dd = S("previewTask");

  Rb = S("checkProtocolTask");

  md = S("validationTask");

  Sb = S("checkStorageTask");

  Uc = S("historyImportTask");

  Tb = S("samplerTask");

  Vb = T("_rlt");

  Wb = S("buildHitTask");

  Xb = S("sendHitTask");

  Vc = S("ceTask");

  zd = S("devIdTask");

  Cd = S("timingTask");

  Ld = S("displayFeaturesTask");

  V = T("name");

  Q = T("clientId", "cid");

  Ad = S("userId", "uid");

  Na = T("trackingId", "tid");

  U = T("cookieName", 0, "_ga");

  W = T("cookieDomain");

  Yb = T("cookiePath", 0, "/");

  Zb = T("cookieExpires", 0, 63072000);

  $b = T("legacyCookieDomain");

  Wc = T("legacyHistoryImport", 0, !0);

  ac = T("storage", 0, "cookie");

  bc = T("allowLinker", 0, !1);

  cc = T("allowAnchor", 0, !0);

  Ka = T("sampleRate", "sf", 100);

  dc = T("siteSpeedSampleRate", 0, 1);

  ec = T("alwaysSendReferrer", 0, !1);

  gd = S("transportUrl");

  Md = S("_r", "_r");

  X = function(a, b, c, d) {
    return b[a] = function() {
      var ca, g;
      try {
        if (d) {
          J(d);
        }
        return c.apply(this, arguments);
      } catch (_error) {
        b = _error;
        g = b && b.name;
        if (!(1 <= 100 * Math.random() || Aa("?"))) {
          ca = ["t=error", "_e=exc", "_v=j31", "sr=1"];
          if (a) {
            ca.push("_f=" + a);
          }
          if (g) {
            ca.push("_m=" + K(g.substring(0, 100)));
          }
          ca.push("aip=1");
          ca.push("z=" + hd());
          Ga(oc() + "/collect", ca.join("&"));
        }
        throw b;
      }
    };
  };

  Od = function() {
    this.V = 10000;
    this.fa = 0;
    this.$ = !1;
    return this.ea = 1;
  };

  Ed = function() {
    var a, b;
    a = new Od;
    if (a.fa && a.$) {
      return 0;
    }
    a.$ = !0;
    if (a.V === 0) {
      return 0;
    }
    if (b === 0) {
      b = Bd();
    }
    if (b % a.V === 0) {
      return Math.floor(b / a.V) % a.ea + 1;
    } else {
      return 0;
    }
  };

  fc = function() {
    var a, b, c, ca, d, e, g, l;
    c = O[oa];
    if (c) {
      c = c.plugins;
    } else {
      c = null;
    }
    if (c && c[y]) {
      d = 0;
      while (d < c.length && !b) {
        e = c[d];
        if (-1 < e[v][t]("Shockwave Flash")) {
          b = e.description;
        }
        d++;
      }
    }
    if (!b) {
      try {
        a = new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7");
        b = a.GetVariable("$version");
      } catch (_error) {
        g = _error;
      }
    }
    if (!b) {
      try {
        a = new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");
        b = "WIN 6,0,21,0";
        a.AllowScriptAccess = "always";
        b = a.GetVariable("$version");
      } catch (_error) {
        ca = _error;
      }
    }
    if (!b) {
      try {
        a = new ActiveXObject("ShockwaveFlash.ShockwaveFlash");
        b = a.GetVariable("$version");
      } catch (_error) {
        l = _error;
      }
    }
    if (b) {
      a = b[m](/[\d]+/g);
      if (3 <= a[y]) {
        b = a[0] + "." + a[1] + " r" + a[2];
      }
    }
    return b || 0;
  };

  gc = function(a, b) {
    var c, d;
    c = Math.min(R(a, dc), 100);
    if (!(La(P(a, Q)) % 100 >= c)) {
      c = {};
      Ec(c) || Fc(c);
      d = c[Eb];
      if (0 === d || Infinity === d || isNaN(d)) {
        if (0 < d) {
          Y(c, Gb);
          Y(c, Jb);
          Y(c, Ib);
          Y(c, Fb);
          Y(c, Hb);
          Y(c, Kb);
          Y(c, Lb);
          return b(c);
        } else {
          return L(window, "load", function() {
            return gc(a, b);
          }, !1);
        }
      }
    }
  };

  Ec = function(a) {
    var b, c;
    b = window.performance || window.webkitPerformance;
    b = b && b.timing;
    if (!b) {
      return !1;
    }
    c = b.navigationStart;
    if (0 === c) {
      return !1;
    }
    a[Eb] = b.loadEventStart - c;
    a[Gb] = b.domainLookupEnd - b.domainLookupStart;
    a[Jb] = b.connectEnd - b.connectStart;
    a[Ib] = b.responseStart - b.requestStart;
    a[Fb] = b.responseEnd - b.responseStart;
    a[Hb] = b.fetchStart - c;
    a[Kb] = b.domInteractive - c;
    a[Lb] = b.domContentLoadedEventStart - c;
    return !0;
  };

  Fc = function(a) {
    var b, c;
    if (window.top !== window) {
      return !1;
    }
    b = window.external;
    c = b && b.onloadT;
    if (b) {
      if (!b.isValidLoadTime) {
        c = 0;
      }
    }
    if (2147483648 < c) {
      c = 0;
    }
    if (0 < c) {
      b.setPageReadyTime();
    }
    if (0 === c) {
      return !1;
    }
    a[Eb] = c;
    return !0;
  };

  Y = function(a, b) {
    var c;
    c = a[b];
    if (isNaN(c) || Infinity === c || c < 0) {
      return a[b] = 0;
    }
  };

  Fd = function(a) {
    return function(b) {
      if (b.get(Va) !== 'pageview' || a.I) {
        a.I = !0;
        return gc(b, function(b) {
          return a[xc]("timing", b);
        });
      }
    };
  };

  hc = !1;

  mc = function(a) {
    var b, c, ca, d, e, g, l, _i, _j, _len;
    if (P(a, ac) === "cookie") {
      b = P(a, U);
      c = nd(a);
      d = kc(P(a, Yb));
      e = lc(P(a, W));
      g = 1000 * R(a, Zb);
      ca = P(a, Na);
      if (e !== "auto") {
        if (zc(b, c, d, e, ca, g)) {
          return hc = !0;
        }
      } else {
        J(32);
        c = [];
        e = xa().split(".");
        l = e[e.length - 1];
        if (4 === e.length && parseInt(l, 10) === l) {
          l = ["none"];
          break;
        }
        for (_i = e.length - 1; _i >= 0; _i += -1) {
          l = e[_i];
          c.push(e.slice(l).join("."));
        }
        c.push("none");
        l = c;
        for (_j = 0, _len = l.length; _j < _len; _j++) {
          e = l[_j];
          a.data.set(W, e);
          c = nd(a);
          if (zc(b, c, d, e, ca, g)) {
            hc = !0;
            return;
          }
        }
        return a.data.set(W, "auto");
      }
    }
  };

  nc = function(a) {
    if ("cookie" === P(a, ac) && !hc && mc(a)) {
      throw "abort";
    }
  };

  Yc = function(a) {
    var b, c, d;
    if (a.get(Wc)) {
      b = P(a, W);
      c = P(a, $b) || xa();
      d = Xc("__utma", c, b);
      if (d) {
        J(19);
        a.set(Tc, (new Date).getTime(), !0);
        a.set(Rc, d.R);
        b = Xc("__utmz", c, b);
        if (d.hash === b.hash) {
          return a.set(Sc, b.R);
        }
      }
    }
  };

  nd = function(a) {
    var b, c;
    b = Cc(P(a, Q));
    c = ic(P(a, W));
    a = jc(P(a, Yb));
    if (1 < a) {
      c += "-" + a;
    }
    return ["GA1", c, b].join(".");
  };

  Gc = function(a, b, c) {
    var d, e, g, l, _i, _len;
    d = [];
    e = [];
    for (_i = 0, _len = a.length; _i < _len; _i++) {
      l = a[_i];
      if (l.r[c] === b) {
        d.push(l);
      } else {
        if (0 === g || l.r[c] < g) {
          e = [l];
          g = l.r[c];
        } else {
          if (l.r[c] === g) {
            e.push(l);
          }
        }
      }
    }
    if (0 < d.length) {
      return d;
    } else {
      return e;
    }
  };

}).call(this);

//# sourceMappingURL=refactoring.js.map
